---
- name: restart boundary-controller daemon
  systemd:
    name: boundary-controller
    state: restarted

- name: restart boundary-worker daemon
  systemd:
    name: boundary-worker
    state: restarted

- name: reload boundary-controller daemon
  systemd:
    name: boundary-controller
    state: restarted
    daemon_reload: yes

- name: reload boundary-worker daemon
  systemd:
    name: boundary-worker
    state: restarted
    daemon_reload: yes
