---
- name: Prepare
  hosts: all
  tasks:
    - name: Update Apt and install dependencies for apt-key
      apt:
        name: ['ca-certificates', 'gnupg']
        update_cache: true
      when: ansible_os_family == 'Debian'
